Update uldk_gugik_dialog.py
MateuszPazio/uldk_gugik_error72 pull request #1
Opened 2024-11-15 11:03 UTC by MateuszPazio

2024-11-18 20:06 UTC, wojtek19022 requested changes
Implementacja w miarę ok, po poprawce literówki wygląda to ok i po poprawkach które naniosłem myślę że śmiało można zmegować

2024-11-18 20:06 UTC, wojtek19022 commented on uldk_gugik.py
> +            self.dlg = UldkGugikDialog()
Tutaj to chyba literówka, powinno być regionFetch

2024-11-18 20:06 UTC, wojtek19022 commented on uldk_gugik_dialog.py
> +            print('Brak danych województw do wypełnienia (tryb offline).')
Proponuję z tego zrobić logi QGIS. Są dostępne fragmenty w kodzie tej wtyczki które za to odpowiadają

2024-11-18 20:06 UTC, wojtek19022 commented on uldk_gugik_dialog.py
> +            print("Brak połączenia z internetem")
Proponuję z tego zrobić logi QGIS. Są dostępne fragmenty w kodzie tej wtyczki które za to odpowiadają

2024-11-19 15:35 UTC, merged

2024-11-19 15:35 UTC, MateuszPazio commented
Done